Create portfolio2
Berucan/Portfolio2 pull request #1
Opened 2022-01-14 14:29 UTC by Berucan

I setup the environment for the project, added linters files, added index file, style file and modified README file, added project description , author details.

2022-01-14 18:13 UTC, Deepakdanger requested changes
Hi @Berucan , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +            <h1 class="heading">About <br/> myself</h1>
- [x] `h1` tag can only use at only one time on each page. Kindly change it to the `h2 or h3` tag.

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +            <p class="info">LET'S CONNECT</p>
- [x]  Here, for `Lets connect` should be in `h2` or any other `hx` tag.

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +              <input type="button" class="btn-tonic" value="Get my resume">
- [x] Here the requirement is :-
- The button (e.g., "Get my resume") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design)

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +          <section class="about">
- [ ] The background color & border-style should be the same as the original website.
- your website
![edit2](https://user-images.githubusercontent.com/26767383/149562551-9be61a44-4743-4b11-a826-e77c45ffd79f.PNG)
- Original website
![o2](https://user-images.githubusercontent.com/26767383/149563378-851138c9-23b2-4e53-9147-d2e5841b766e.PNG)

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +              <ul class="language-list">
- [ ] Here the design should same as the original website.
- your website
![edit1](https://user-images.githubusercontent.com/26767383/149563604-2446bc36-16b4-4c62-8fa6-e84c4afd8df8.PNG)
- Original website
![original1](https://user-images.githubusercontent.com/26767383/149563639-d9ab602e-f0fd-4a70-b4a3-27b1d8a0bcc0.PNG)

2022-01-14 18:13 UTC, Deepakdanger commented on index.html
> +          <section class="work">
-[ ] Here work section background color, border, the margin should match the original website.
- your website
![edit3](https://user-images.githubusercontent.com/26767383/149564713-7f7aca64-3e06-4553-a661-d153e54f4005.PNG)

- Original website  
![o3](https://user-images.githubusercontent.com/26767383/149564676-fd53d3b6-e888-432a-b1ae-9a89fa8f9202.PNG)

2022-01-15 10:38 UTC, lily-coder reviewed
Hi @Berucan , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors. Please fix the linter errors and submit for another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-01-15 12:41 UTC, Hamzaoutdoors approved these changes
Hi @Berucan, 

## Congratulations! 🎉 Project Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀

To Highlight:

- [x] The Pull Request has a proper title and description. ✔️
- [x] You have added a descriptive Readme file. Good Job. ✔️
- [x] There is no linter error is present. ✔️
- [x] Project has met all the technical aspects you needed for this project! ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] 
You have broken links in your README such as `Live demo` and `MIT` links, so Kindly try to address that, because keeping broken links in the readme file can be unprofessional

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 12:47 UTC, merged